[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  SITE_ENV = "production"

[context.deploy-preview.environment]
  SITE_ENV = "staging"

[context.branch-deploy.environment]
  SITE_ENV = "staging"
