/**
 * Word Helper — Curated Word Lists
 * Hand-curated word lists (selection + plain-English meanings) maintained by Word Helper.
 */

export const wordListsHubData = {
  href: "/word-lists/",
  title: "Word Lists",
  h1: "English Word Lists",
  metaTitle: "English Word Lists — Common, Positive, Academic, and More | Word Helper",
  metaDescription:
    "Browse curated English word lists: common words, positive words, academic vocabulary, strong verbs, descriptive adjectives, and words for writers.",
  intro:
    "Curated word lists for learners, writers, and word game players. Each list includes meanings, examples, and links to full word pages where available.",
  answer:
    "Word Helper's word lists are grouped by theme and purpose. Each entry includes the word, its part of speech, a brief meaning, and an example sentence. Lists are designed to be useful for vocabulary building, writing, studying, and word games.",
};

// ── Helper: mark words that have full word pages ───────────────────
const withPage = (word) => ({ ...word, wordPageHref: `/word/${word.word}/` });
const noPage = (word) => ({ ...word, wordPageHref: null });

// ── List 1: 50 Common English Words ───────────────────────────────
export const commonEnglishWords = {
  id: "common-english-words",
  audience: "English learners and anyone building everyday vocabulary.",
  useCases: ["Build core vocabulary for reading and conversation","Practice spelling of high-frequency words","Use as flashcards or daily writing prompts"],
  tip: "Master the most common words first — they carry most of everyday meaning.",
  href: "/word-lists/common-english-words/",
  title: "50 Common English Words Every Learner Should Know",
  h1: "50 Common English Words",
  metaTitle: "50 Common English Words Every Learner Should Know | Word Helper",
  metaDescription:
    "A curated list of 50 common English words with meanings and example sentences. Ideal for learners at any level building a solid English foundation.",
  intro: "Fifty of the most useful everyday English words — each with a meaning and example sentence.",
  answer:
    "Learning the most common English words gives you the foundation for understanding and using everyday English. These 50 words cover nouns, verbs, and adjectives that appear in almost every conversation, article, and story.",
  category: "Vocabulary",
  difficulty: "beginner",
  wordCount: 50,
  words: [
    withPage({ word: "learn", partOfSpeech: "verb", meaning: "To gain knowledge or skill through study or experience.", example: "She went to the library to learn more about history." }),
    withPage({ word: "change", partOfSpeech: "verb / noun", meaning: "To become or make different; a difference.", example: "The weather can change quickly in autumn." }),
    withPage({ word: "understand", partOfSpeech: "verb", meaning: "To know the meaning of something.", example: "He listened carefully to understand the instructions." }),
    withPage({ word: "important", partOfSpeech: "adjective", meaning: "Having great value or effect.", example: "It is important to drink enough water each day." }),
    withPage({ word: "strong", partOfSpeech: "adjective", meaning: "Powerful, firm, or hard to break.", example: "The bridge was built from strong steel beams." }),
    withPage({ word: "simple", partOfSpeech: "adjective", meaning: "Not complicated; easy to understand.", example: "The instructions were clear and simple to follow." }),
    withPage({ word: "create", partOfSpeech: "verb", meaning: "To make something new.", example: "She used paint and canvas to create a landscape." }),
    withPage({ word: "remember", partOfSpeech: "verb", meaning: "To bring something from the past back to mind.", example: "He tried to remember where he had left his keys." }),
    withPage({ word: "happy", partOfSpeech: "adjective", meaning: "Feeling joy or pleasure.", example: "The children were happy when school ended for the summer." }),
    withPage({ word: "discover", partOfSpeech: "verb", meaning: "To find or learn something previously unknown.", example: "Scientists discovered a new species of fish in the deep ocean." }),
    noPage({ word: "work", partOfSpeech: "verb / noun", meaning: "Activity done to achieve a result; a job or task.", example: "She works at a hospital as a nurse." }),
    noPage({ word: "time", partOfSpeech: "noun", meaning: "The measured progress of events from past to future.", example: "We arrived at the station with time to spare." }),
    noPage({ word: "year", partOfSpeech: "noun", meaning: "A period of twelve months.", example: "He spent a year studying abroad." }),
    noPage({ word: "day", partOfSpeech: "noun", meaning: "The period of light between sunrise and sunset.", example: "They planned to go hiking on a clear day." }),
    noPage({ word: "place", partOfSpeech: "noun / verb", meaning: "A specific location; to put something somewhere.", example: "The park is a good place to relax." }),
    noPage({ word: "people", partOfSpeech: "noun", meaning: "More than one person; human beings.", example: "People from all over the city came to the festival." }),
    noPage({ word: "way", partOfSpeech: "noun", meaning: "A method, path, or manner of doing something.", example: "There is more than one way to solve this problem." }),
    noPage({ word: "life", partOfSpeech: "noun", meaning: "The state of being alive; experience of living.", example: "She lived a full and interesting life." }),
    noPage({ word: "world", partOfSpeech: "noun", meaning: "The Earth and all living things on it.", example: "The world is a large and varied place." }),
    noPage({ word: "hand", partOfSpeech: "noun / verb", meaning: "The body part at the end of the arm; to give something.", example: "He raised his hand to answer the question." }),
    noPage({ word: "part", partOfSpeech: "noun / verb", meaning: "A piece or section of a whole; to separate.", example: "She read the first part of the book in one sitting." }),
    noPage({ word: "home", partOfSpeech: "noun / adjective", meaning: "The place where a person lives.", example: "After a long trip, it felt good to be home." }),
    noPage({ word: "water", partOfSpeech: "noun / verb", meaning: "The clear liquid essential for life; to pour water on plants.", example: "He drank a glass of cold water after exercise." }),
    noPage({ word: "room", partOfSpeech: "noun", meaning: "A separate space within a building; available space.", example: "The living room was bright and comfortable." }),
    noPage({ word: "money", partOfSpeech: "noun", meaning: "A medium of exchange used to buy things.", example: "She saved money for months to buy the bicycle." }),
    noPage({ word: "number", partOfSpeech: "noun / verb", meaning: "A mathematical value; to count or assign numbers.", example: "Each student received a different number." }),
    noPage({ word: "word", partOfSpeech: "noun", meaning: "A single unit of language with a meaning.", example: "He could not find the right word to express his feeling." }),
    noPage({ word: "night", partOfSpeech: "noun", meaning: "The dark period between sunset and sunrise.", example: "The stars are brightest on a clear night." }),
    noPage({ word: "point", partOfSpeech: "noun / verb", meaning: "A specific detail, position, or sharp tip; to direct attention.", example: "She made a good point during the meeting." }),
    noPage({ word: "story", partOfSpeech: "noun", meaning: "An account or narrative of events.", example: "He told a story about his travels in the mountains." }),
    noPage({ word: "fact", partOfSpeech: "noun", meaning: "A piece of information that is verified and true.", example: "The fact is that regular exercise improves health." }),
    noPage({ word: "book", partOfSpeech: "noun / verb", meaning: "A set of printed or written pages; to reserve something.", example: "She borrowed a book about birds from the library." }),
    noPage({ word: "eye", partOfSpeech: "noun / verb", meaning: "The organ used for seeing; to look at closely.", example: "She kept her eye on the ball during the game." }),
    noPage({ word: "job", partOfSpeech: "noun", meaning: "A task or paid position of work.", example: "He started a new job at a design studio." }),
    noPage({ word: "friend", partOfSpeech: "noun", meaning: "A person you trust and enjoy spending time with.", example: "She called a friend to share the good news." }),
    noPage({ word: "house", partOfSpeech: "noun / verb", meaning: "A building where people live; to provide shelter.", example: "They moved into the house after the renovation was complete." }),
    noPage({ word: "family", partOfSpeech: "noun", meaning: "A group of people related by blood or close ties.", example: "Her family gathered for a meal every Sunday." }),
    noPage({ word: "power", partOfSpeech: "noun / verb", meaning: "The ability to do, influence, or control; to supply energy.", example: "Knowledge gives you the power to make better decisions." }),
    noPage({ word: "city", partOfSpeech: "noun", meaning: "A large, populated urban area.", example: "The city lights were visible from miles away." }),
    noPage({ word: "food", partOfSpeech: "noun", meaning: "Any substance eaten to nourish the body.", example: "They shared a meal of fresh, local food." }),
    noPage({ word: "question", partOfSpeech: "noun / verb", meaning: "A sentence that asks for information; to ask or challenge.", example: "She raised her hand to ask a question." }),
    noPage({ word: "idea", partOfSpeech: "noun", meaning: "A thought, plan, or mental image.", example: "He had an idea for a new product." }),
    noPage({ word: "system", partOfSpeech: "noun", meaning: "A set of connected things or parts working together.", example: "The school has a clear system for reporting absences." }),
    noPage({ word: "body", partOfSpeech: "noun", meaning: "The physical structure of a person or animal.", example: "Regular movement keeps the body healthy." }),
    noPage({ word: "school", partOfSpeech: "noun / verb", meaning: "A place of education; to teach or train.", example: "The children walked to school together each morning." }),
    noPage({ word: "month", partOfSpeech: "noun", meaning: "One of the twelve named divisions of a year.", example: "She visited her parents once a month." }),
    noPage({ word: "side", partOfSpeech: "noun / adjective", meaning: "One edge or direction; not the main part.", example: "The café is on the left side of the street." }),
    noPage({ word: "area", partOfSpeech: "noun", meaning: "A region or section of a place or subject.", example: "They explored the area around the lake." }),
    noPage({ word: "head", partOfSpeech: "noun / verb", meaning: "The top part of the body; to lead or go in a direction.", example: "She is the head of the research team." }),
    noPage({ word: "sound", partOfSpeech: "noun / verb / adjective", meaning: "Something heard; to produce a noise; healthy and solid.", example: "The sound of rain helped her fall asleep." }),
    noPage({ word: "hour", partOfSpeech: "noun", meaning: "A period of sixty minutes.", example: "The journey takes about an hour by train." }),
  ],
};

// ── List 2: 50 Positive English Words ────────────────────────────
export const positiveWords = {
  id: "positive-words",
  audience: "Writers, students, and anyone reaching for warmer, more uplifting language.",
  useCases: ["Add warmth to messages, reviews, and notes","Find stronger alternatives to \"good\" or \"nice\"","Build a positive-vocabulary word bank"],
  tip: "Match a word’s intensity to the moment — “content” and “elated” are both positive but very different.",
  href: "/word-lists/positive-words/",
  title: "50 Positive English Words to Uplift and Inspire",
  h1: "50 Positive English Words",
  metaTitle: "50 Positive English Words — Uplifting Vocabulary | Word Helper",
  metaDescription:
    "Discover 50 positive English words that express joy, strength, and optimism. Each word includes a meaning and example sentence.",
  intro: "Fifty words that express positivity, strength, gratitude, and hope — with meanings and examples.",
  answer:
    "Positive vocabulary helps you express good experiences, emotions, and attitudes clearly. These 50 words cover feelings of joy and gratitude, qualities of strength and resilience, and actions that inspire and uplift.",
  category: "Vocabulary",
  difficulty: "beginner to intermediate",
  wordCount: 50,
  words: [
    withPage({ word: "amazing", partOfSpeech: "adjective", meaning: "Causing great surprise or wonder.", example: "The view from the mountain was absolutely amazing." }),
    withPage({ word: "beautiful", partOfSpeech: "adjective", meaning: "Extremely pleasing to the senses or the mind.", example: "She wrote a beautiful letter to her grandmother." }),
    withPage({ word: "courage", partOfSpeech: "noun", meaning: "The ability to face difficulty with confidence.", example: "It took courage to speak honestly in front of the group." }),
    withPage({ word: "excellent", partOfSpeech: "adjective", meaning: "Extremely good; meeting a very high standard.", example: "His presentation received excellent feedback from the panel." }),
    withPage({ word: "freedom", partOfSpeech: "noun", meaning: "The state of being free to act without restriction.", example: "She felt a sense of freedom when she moved to the new city." }),
    withPage({ word: "grateful", partOfSpeech: "adjective", meaning: "Feeling or showing appreciation for something received.", example: "He was deeply grateful for the help he received." }),
    withPage({ word: "happy", partOfSpeech: "adjective", meaning: "Feeling joy or satisfaction.", example: "She felt happy when she heard the good news." }),
    withPage({ word: "wonder", partOfSpeech: "noun / verb", meaning: "A feeling of amazed curiosity; to think curiously.", example: "He looked at the night sky with wonder." }),
    withPage({ word: "achieve", partOfSpeech: "verb", meaning: "To reach a goal through effort.", example: "With hard work, anyone can achieve their goals." }),
    withPage({ word: "powerful", partOfSpeech: "adjective", meaning: "Having great strength or effect.", example: "Her speech was powerful and moved the audience deeply." }),
    noPage({ word: "joyful", partOfSpeech: "adjective", meaning: "Feeling or expressing great happiness.", example: "The crowd was joyful when the team won." }),
    noPage({ word: "radiant", partOfSpeech: "adjective", meaning: "Clearly happy and glowing with positive energy.", example: "She looked radiant on her graduation day." }),
    noPage({ word: "hopeful", partOfSpeech: "adjective", meaning: "Feeling optimistic about the future.", example: "He remained hopeful that the project would succeed." }),
    noPage({ word: "vibrant", partOfSpeech: "adjective", meaning: "Full of energy, enthusiasm, and life.", example: "The market was vibrant with colour and sound." }),
    noPage({ word: "kind", partOfSpeech: "adjective", meaning: "Caring, generous, and gentle toward others.", example: "She was kind enough to help the stranger find the station." }),
    noPage({ word: "inspire", partOfSpeech: "verb", meaning: "To fill someone with motivation or creative energy.", example: "The story of her journey inspired many young readers." }),
    noPage({ word: "thrive", partOfSpeech: "verb", meaning: "To grow and do well; to prosper.", example: "Plants thrive when given enough sunlight and water." }),
    noPage({ word: "bright", partOfSpeech: "adjective", meaning: "Giving out or filled with light; intelligent and cheerful.", example: "The bright classroom made studying feel more pleasant." }),
    noPage({ word: "gentle", partOfSpeech: "adjective", meaning: "Soft, calm, and mild in manner or touch.", example: "She spoke in a gentle voice to comfort the child." }),
    noPage({ word: "honest", partOfSpeech: "adjective", meaning: "Truthful and straightforward; free from deception.", example: "He gave an honest answer even though it was difficult to hear." }),
    noPage({ word: "calm", partOfSpeech: "adjective", meaning: "Not anxious or agitated; quiet and peaceful.", example: "She remained calm during the unexpected delay." }),
    noPage({ word: "energetic", partOfSpeech: "adjective", meaning: "Having lots of energy and enthusiasm.", example: "The energetic coach motivated the team before the match." }),
    noPage({ word: "generous", partOfSpeech: "adjective", meaning: "Willing to give more than is expected.", example: "He was generous with his time and expertise." }),
    noPage({ word: "confident", partOfSpeech: "adjective", meaning: "Feeling sure of your own abilities.", example: "She felt confident going into the interview." }),
    noPage({ word: "creative", partOfSpeech: "adjective", meaning: "Able to produce original and imaginative ideas.", example: "The creative design caught everyone's attention." }),
    noPage({ word: "resilient", partOfSpeech: "adjective", meaning: "Able to recover from difficulty or change.", example: "After the setback, she showed how resilient she could be." }),
    noPage({ word: "mindful", partOfSpeech: "adjective", meaning: "Aware and attentive to the present moment.", example: "Being mindful of others' feelings helps build strong relationships." }),
    noPage({ word: "curious", partOfSpeech: "adjective", meaning: "Eager to learn or know about things.", example: "He was curious about how the machine worked." }),
    noPage({ word: "warm", partOfSpeech: "adjective", meaning: "Friendly and kind in manner.", example: "She greeted the new student with a warm smile." }),
    noPage({ word: "peaceful", partOfSpeech: "adjective", meaning: "Free from disturbance; quiet and calm.", example: "The countryside was peaceful after the busy city." }),
    noPage({ word: "passionate", partOfSpeech: "adjective", meaning: "Showing strong enthusiasm and emotion.", example: "She is passionate about protecting the environment." }),
    noPage({ word: "brave", partOfSpeech: "adjective", meaning: "Ready to face danger or difficulty without fear.", example: "It was brave of him to speak up against the unfair decision." }),
    noPage({ word: "patient", partOfSpeech: "adjective", meaning: "Able to wait or deal with difficulty without frustration.", example: "A patient teacher explains things as many times as needed." }),
    noPage({ word: "wise", partOfSpeech: "adjective", meaning: "Having experience and good judgement.", example: "Her grandmother gave wise advice about handling conflict." }),
    noPage({ word: "focus", partOfSpeech: "noun / verb", meaning: "Concentration on a single thing; to direct your attention.", example: "With better focus, she finished the report in two hours." }),
    noPage({ word: "joy", partOfSpeech: "noun", meaning: "A strong feeling of happiness and pleasure.", example: "The sound of the children laughing brought her joy." }),
    noPage({ word: "hope", partOfSpeech: "noun / verb", meaning: "A feeling that something good will happen; to wish for something.", example: "Even in difficult times, hope keeps people going." }),
    noPage({ word: "grow", partOfSpeech: "verb", meaning: "To increase in size, knowledge, or strength over time.", example: "She watched her confidence grow with each new experience." }),
    noPage({ word: "persist", partOfSpeech: "verb", meaning: "To keep going despite obstacles.", example: "He persisted through the challenges and eventually succeeded." }),
    noPage({ word: "flourish", partOfSpeech: "verb", meaning: "To grow or develop in a healthy and successful way.", example: "The business began to flourish after moving to a better location." }),
    noPage({ word: "progress", partOfSpeech: "noun / verb", meaning: "Forward or positive development; to move forward.", example: "The team made steady progress toward their goal." }),
    noPage({ word: "support", partOfSpeech: "noun / verb", meaning: "Help or encouragement given to someone; to help or uphold.", example: "Her family's support made a big difference during difficult times." }),
    noPage({ word: "trust", partOfSpeech: "noun / verb", meaning: "Firm belief in someone's honesty or ability; to believe in.", example: "Trust between team members makes collaboration easier." }),
    noPage({ word: "improve", partOfSpeech: "verb", meaning: "To make or become better.", example: "Regular practice will improve your reading speed." }),
    noPage({ word: "celebrate", partOfSpeech: "verb", meaning: "To mark a special event or achievement with festivities.", example: "They gathered to celebrate her promotion at work." }),
    noPage({ word: "appreciate", partOfSpeech: "verb", meaning: "To recognise and value the quality or importance of something.", example: "She appreciated how much effort had gone into the project." }),
    noPage({ word: "embrace", partOfSpeech: "verb", meaning: "To accept willingly and enthusiastically; to hug.", example: "He was encouraged to embrace new challenges at work." }),
    noPage({ word: "inspire", partOfSpeech: "verb", meaning: "To fill someone with motivation or creative energy.", example: "Her story inspired others to follow their own dreams." }),
    noPage({ word: "uplift", partOfSpeech: "verb", meaning: "To raise the mood or spirit of someone.", example: "A kind word can uplift someone who is having a hard day." }),
    noPage({ word: "harmony", partOfSpeech: "noun", meaning: "A pleasing balance and agreement between parts.", example: "The team worked in harmony to complete the project on time." }),
    noPage({ word: "gratitude", partOfSpeech: "noun", meaning: "The feeling of being thankful.", example: "She expressed her gratitude with a handwritten note." }),
  ],
};

// ── List 3: 40 Academic English Words ────────────────────────────
export const academicWords = {
  id: "academic-words",
  audience: "Students and writers working on essays, reports, and formal writing.",
  useCases: ["Strengthen essays and research writing","Prepare for academic and exam vocabulary","Replace casual words with precise, formal ones"],
  tip: "Use an academic word where it adds precision — not just to sound formal.",
  href: "/word-lists/academic-words/",
  title: "40 Essential Academic English Words",
  h1: "40 Academic English Words",
  metaTitle: "40 Essential Academic English Words for Study and Writing | Word Helper",
  metaDescription:
    "Master 40 key academic English words used in essays, research, and formal writing. Each word includes a meaning and example sentence.",
  intro: "Forty academic words that appear in essays, research, and formal writing — with meanings and examples.",
  answer:
    "Academic English has its own vocabulary. Words like analyse, evaluate, and hypothesis appear repeatedly in textbooks, essays, and formal writing. Learning these words helps you read and write in academic contexts more effectively.",
  category: "Academic",
  difficulty: "intermediate to advanced",
  wordCount: 40,
  words: [
    withPage({ word: "analyse", partOfSpeech: "verb", meaning: "To examine something in detail to understand it.", example: "Students were asked to analyse the poem's use of imagery." }),
    withPage({ word: "knowledge", partOfSpeech: "noun", meaning: "Information, facts, or skills gained through experience or education.", example: "The course deepened her knowledge of economic theory." }),
    withPage({ word: "experience", partOfSpeech: "noun / verb", meaning: "Practical contact with and observation of events; to have or feel.", example: "Field research gave students direct experience of the subject." }),
    withPage({ word: "understand", partOfSpeech: "verb", meaning: "To grasp the meaning or significance of something.", example: "Researchers seek to understand the causes of climate change." }),
    withPage({ word: "challenge", partOfSpeech: "noun / verb", meaning: "A difficult task; to question or dispute a claim.", example: "The data challenged the existing theory." }),
    noPage({ word: "analyse", partOfSpeech: "verb", meaning: "To examine something carefully and in detail.", example: "The report analyses the impact of the new policy on employment." }),
    noPage({ word: "evaluate", partOfSpeech: "verb", meaning: "To judge or assess the quality or importance of something.", example: "The committee evaluated each proposal before making a decision." }),
    noPage({ word: "hypothesis", partOfSpeech: "noun", meaning: "An educated guess or proposed explanation to be tested.", example: "The scientist tested her hypothesis with a series of experiments." }),
    noPage({ word: "conclude", partOfSpeech: "verb", meaning: "To reach a decision or judgement at the end of reasoning.", example: "Based on the evidence, the report concludes that action is needed." }),
    noPage({ word: "evidence", partOfSpeech: "noun", meaning: "Information that supports or proves something.", example: "The study presented clear evidence for the treatment's effectiveness." }),
    noPage({ word: "significant", partOfSpeech: "adjective", meaning: "Important enough to have a noticeable effect or meaning.", example: "There was a significant increase in sales after the campaign." }),
    noPage({ word: "define", partOfSpeech: "verb", meaning: "To give the exact meaning of a word or concept.", example: "The first paragraph should define the key terms used in the essay." }),
    noPage({ word: "compare", partOfSpeech: "verb", meaning: "To look at the similarities and differences between things.", example: "The essay compares two approaches to solving the problem." }),
    noPage({ word: "contrast", partOfSpeech: "verb / noun", meaning: "To show the differences between two or more things; a difference.", example: "In contrast to the first method, the second one is faster." }),
    noPage({ word: "context", partOfSpeech: "noun", meaning: "The circumstances in which something happens or is understood.", example: "Understanding the historical context helps interpret the text." }),
    noPage({ word: "theory", partOfSpeech: "noun", meaning: "A set of ideas intended to explain something.", example: "Darwin's theory of evolution changed the science of biology." }),
    noPage({ word: "research", partOfSpeech: "noun / verb", meaning: "Systematic study to discover facts; to carry out such study.", example: "Her research involved surveys with over 500 participants." }),
    noPage({ word: "structure", partOfSpeech: "noun / verb", meaning: "The way something is organised or built; to arrange in a logical way.", example: "A clear structure helps readers follow an argument." }),
    noPage({ word: "argument", partOfSpeech: "noun", meaning: "A reasoned set of points supporting a position.", example: "The essay presents a strong argument for renewable energy." }),
    noPage({ word: "approach", partOfSpeech: "noun / verb", meaning: "A way of dealing with something; to come near or begin.", example: "The author takes a historical approach to studying language change." }),
    noPage({ word: "factor", partOfSpeech: "noun", meaning: "A thing that contributes to a result.", example: "Diet is one of several factors that affect overall health." }),
    noPage({ word: "influence", partOfSpeech: "noun / verb", meaning: "The effect one thing has on another; to affect or shape.", example: "Cultural factors influence how language is used in different contexts." }),
    noPage({ word: "outcome", partOfSpeech: "noun", meaning: "The result or consequence of an action or situation.", example: "The outcome of the experiment was not what the team expected." }),
    noPage({ word: "indicate", partOfSpeech: "verb", meaning: "To point to or suggest something.", example: "The data indicates a rise in global temperatures over the past decade." }),
    noPage({ word: "interpret", partOfSpeech: "verb", meaning: "To explain or give meaning to something.", example: "Readers may interpret the poem's ending in different ways." }),
    noPage({ word: "method", partOfSpeech: "noun", meaning: "A way of doing something systematically.", example: "The research method involved both interviews and observation." }),
    noPage({ word: "perspective", partOfSpeech: "noun", meaning: "A particular way of thinking about or viewing something.", example: "The essay considers the problem from a sociological perspective." }),
    noPage({ word: "concept", partOfSpeech: "noun", meaning: "An abstract idea or general principle.", example: "The concept of justice varies across different legal systems." }),
    noPage({ word: "process", partOfSpeech: "noun / verb", meaning: "A series of steps to achieve an outcome; to perform such steps.", example: "The editorial process involves multiple rounds of review." }),
    noPage({ word: "data", partOfSpeech: "noun", meaning: "Facts and figures collected for analysis.", example: "The data collected from surveys was organised into a table." }),
    noPage({ word: "identify", partOfSpeech: "verb", meaning: "To recognise and name something.", example: "The study aims to identify the main causes of the problem." }),
    noPage({ word: "impact", partOfSpeech: "noun / verb", meaning: "A strong effect; to have a strong effect on.", example: "Climate change has a measurable impact on coastal communities." }),
    noPage({ word: "sufficient", partOfSpeech: "adjective", meaning: "Enough for the purpose.", example: "Is there sufficient evidence to support this claim?" }),
    noPage({ word: "primary", partOfSpeech: "adjective", meaning: "Most important; of the first stage.", example: "The primary goal of the project is to improve health outcomes." }),
    noPage({ word: "source", partOfSpeech: "noun / verb", meaning: "The origin or place where something comes from; to find and get.", example: "Academic writing requires citing every source used." }),
    noPage({ word: "review", partOfSpeech: "noun / verb", meaning: "A critical assessment; to look at and assess carefully.", example: "The committee will review all submitted proposals next week." }),
    noPage({ word: "contribute", partOfSpeech: "verb", meaning: "To give or add something to a combined result.", example: "Each member was expected to contribute ideas to the discussion." }),
    noPage({ word: "establish", partOfSpeech: "verb", meaning: "To set up or prove something firmly.", example: "The findings help establish a clear link between sleep and memory." }),
    noPage({ word: "assume", partOfSpeech: "verb", meaning: "To suppose something is true without proof.", example: "Do not assume the reader already knows the technical terms." }),
    noPage({ word: "demonstrate", partOfSpeech: "verb", meaning: "To show or prove something clearly.", example: "The experiment demonstrates that plants grow faster with more light." }),
  ],
};

// ── List 4: 40 Words for Writers ─────────────────────────────────
export const wordsForWriters = {
  id: "words-for-writers",
  audience: "Writers, editors, and storytellers who want sharper prose.",
  useCases: ["Replace vague words with vivid, precise ones","Vary word choice to avoid repetition","Set tone in fiction, essays, and copy"],
  tip: "One precise word usually beats two vague ones.",
  href: "/word-lists/words-for-writers/",
  title: "40 Powerful Words for Writers and Storytellers",
  h1: "40 Words for Writers and Storytellers",
  metaTitle: "40 Powerful Words for Writers and Storytellers | Word Helper",
  metaDescription:
    "Discover 40 vivid, literary English words that help writers create stronger prose and richer stories. Each includes a meaning and example.",
  intro: "Forty vivid, precise words to make writing stronger, clearer, and more memorable.",
  answer:
    "Strong writing depends on choosing the right word for the right moment. These 40 words — vivid verbs, precise adjectives, and expressive nouns — help writers move beyond vague language and find words that carry meaning and feeling.",
  category: "Writing",
  difficulty: "intermediate",
  wordCount: 40,
  words: [
    withPage({ word: "wonder", partOfSpeech: "noun / verb", meaning: "A deep sense of amazement; to think curiously.", example: "She gazed at the ancient ruins with quiet wonder." }),
    withPage({ word: "discover", partOfSpeech: "verb", meaning: "To find something previously unknown.", example: "He discovered a box of old letters in the attic." }),
    withPage({ word: "change", partOfSpeech: "verb / noun", meaning: "A transformation; to become or make different.", example: "The story follows a character who must change or perish." }),
    withPage({ word: "courage", partOfSpeech: "noun", meaning: "Facing difficulty with strength of mind.", example: "It took courage to write honestly about her own failures." }),
    withPage({ word: "freedom", partOfSpeech: "noun", meaning: "The state of being free from constraint.", example: "The character's quest for freedom drives the entire plot." }),
    noPage({ word: "vivid", partOfSpeech: "adjective", meaning: "Producing clear and striking mental images.", example: "Her vivid description of the market made it feel real." }),
    noPage({ word: "haunt", partOfSpeech: "verb", meaning: "To persist in the mind; to linger in a place.", example: "The memory of that afternoon haunted him for years." }),
    noPage({ word: "linger", partOfSpeech: "verb", meaning: "To stay somewhere or in someone's mind longer than expected.", example: "The smell of bread lingered in the kitchen long after breakfast." }),
    noPage({ word: "shatter", partOfSpeech: "verb", meaning: "To break suddenly into many pieces; to destroy completely.", example: "A single phone call shattered his sense of security." }),
    noPage({ word: "unravel", partOfSpeech: "verb", meaning: "To undo or come apart; to begin to fall apart.", example: "The plan began to unravel as soon as they arrived." }),
    noPage({ word: "whisper", partOfSpeech: "verb / noun", meaning: "To speak very softly; a very soft sound or voice.", example: "She whispered the answer so only he could hear." }),
    noPage({ word: "glimmer", partOfSpeech: "noun / verb", meaning: "A faint or wavering light; a small sign of something.", example: "There was a glimmer of hope in an otherwise dark situation." }),
    noPage({ word: "surge", partOfSpeech: "verb / noun", meaning: "A sudden strong rush of feeling or movement.", example: "A surge of energy ran through the crowd when the music started." }),
    noPage({ word: "unsettle", partOfSpeech: "verb", meaning: "To make someone feel anxious or disturbed.", example: "The silence in the house unsettled her more than noise would have." }),
    noPage({ word: "luminous", partOfSpeech: "adjective", meaning: "Softly bright or glowing; clear and radiant.", example: "The moon was luminous over the still water." }),
    noPage({ word: "fierce", partOfSpeech: "adjective", meaning: "Intense, powerful, and often aggressive.", example: "The wind was fierce enough to knock over signs on the street." }),
    noPage({ word: "tender", partOfSpeech: "adjective", meaning: "Gentle, kind, and showing affection.", example: "She placed a tender hand on his shoulder." }),
    noPage({ word: "ache", partOfSpeech: "verb / noun", meaning: "A dull persistent pain; to feel such a pain.", example: "She ached for a familiar voice after weeks alone." }),
    noPage({ word: "dissolve", partOfSpeech: "verb", meaning: "To melt into liquid; to gradually disappear.", example: "His confidence dissolved when he saw the crowd." }),
    noPage({ word: "still", partOfSpeech: "adjective / adverb", meaning: "Not moving; continuing up to the present.", example: "The lake was perfectly still in the early morning." }),
    noPage({ word: "hollow", partOfSpeech: "adjective / noun", meaning: "Empty inside; a feeling of emptiness.", example: "After the argument, he felt hollow and tired." }),
    noPage({ word: "brittle", partOfSpeech: "adjective", meaning: "Easily broken; sharp and cold in tone.", example: "Her smile was brittle, as if one more word would break it." }),
    noPage({ word: "gather", partOfSpeech: "verb", meaning: "To bring together; to collect or build up.", example: "Clouds gathered on the horizon before the storm." }),
    noPage({ word: "bare", partOfSpeech: "adjective", meaning: "Without covering; minimal and exposed.", example: "The bare walls of the abandoned house felt cold and unwelcoming." }),
    noPage({ word: "shimmer", partOfSpeech: "verb / noun", meaning: "To shine with a soft trembling light.", example: "The heat made the road ahead shimmer in the distance." }),
    noPage({ word: "raw", partOfSpeech: "adjective", meaning: "Unprocessed, honest, and sometimes painful.", example: "The poem's raw emotion caught many readers off guard." }),
    noPage({ word: "fracture", partOfSpeech: "verb / noun", meaning: "To crack or break; a crack or break.", example: "Trust between the characters fractures early in the story." }),
    noPage({ word: "weight", partOfSpeech: "noun", meaning: "The heaviness of something; a feeling of burden.", example: "She carried the weight of her decision quietly for months." }),
    noPage({ word: "silence", partOfSpeech: "noun / verb", meaning: "The complete absence of sound; to make someone stop speaking.", example: "A long silence followed her admission." }),
    noPage({ word: "urgent", partOfSpeech: "adjective", meaning: "Requiring immediate action or attention.", example: "An urgent tone in the letter made her stop everything else." }),
    noPage({ word: "drift", partOfSpeech: "verb / noun", meaning: "To move slowly with no direction; an aimless movement.", example: "Her thoughts began to drift as she waited." }),
    noPage({ word: "anchor", partOfSpeech: "noun / verb", meaning: "Something that holds firmly; to hold something in place.", example: "Her routine became an anchor during an uncertain period." }),
    noPage({ word: "unspoken", partOfSpeech: "adjective", meaning: "Not said out loud; understood without words.", example: "There was an unspoken agreement between them to never discuss it." }),
    noPage({ word: "stark", partOfSpeech: "adjective", meaning: "Sharply clear and harsh; bare and without comfort.", example: "The contrast between the two characters was stark and deliberate." }),
    noPage({ word: "echo", partOfSpeech: "verb / noun", meaning: "To repeat or resemble; a repetition of a sound or idea.", example: "The final scene echoes the opening one, creating a full circle." }),
    noPage({ word: "tension", partOfSpeech: "noun", meaning: "A feeling of anxious suspense; a strained state.", example: "Tension built slowly through the first half of the story." }),
    noPage({ word: "unfold", partOfSpeech: "verb", meaning: "To open out; to happen gradually and be revealed.", example: "Events began to unfold faster than any character expected." }),
    noPage({ word: "fragile", partOfSpeech: "adjective", meaning: "Easily broken or damaged; delicate.", example: "The relationship was still fragile after the argument." }),
    noPage({ word: "pause", partOfSpeech: "verb / noun", meaning: "To stop briefly; a short break.", example: "He paused before answering, choosing his words carefully." }),
    noPage({ word: "pulse", partOfSpeech: "noun / verb", meaning: "A rhythmic beat; to beat rhythmically.", example: "She could feel the pulse of the city even at midnight." }),
  ],
};

// ── List 5: 40 Strong Action Verbs ────────────────────────────────
export const strongActionVerbs = {
  id: "strong-action-verbs",
  audience: "Writers, resume-builders, and anyone tightening their prose.",
  useCases: ["Make resumes and cover letters more direct","Replace weak verb-plus-adverb pairs with one strong verb","Energize fiction and marketing copy"],
  tip: "Prefer “sprinted” over “ran quickly” — a strong verb does the work of several words.",
  href: "/word-lists/strong-action-verbs/",
  title: "40 Strong Action Verbs for Writing and Communication",
  h1: "40 Strong Action Verbs",
  metaTitle: "40 Strong Action Verbs for Writing and Communication | Word Helper",
  metaDescription:
    "Replace weak verbs with 40 strong, precise action verbs. Each includes a meaning and example to show how it upgrades your writing.",
  intro: "Forty strong, precise verbs to replace vague or weak language in writing, emails, and speech.",
  answer:
    "Strong verbs make writing direct and clear. Instead of 'he made a change', say 'he transformed'. Instead of 'she did the work', say 'she executed the plan'. These 40 verbs replace weak phrasing with confident, precise language.",
  category: "Writing",
  difficulty: "intermediate",
  wordCount: 40,
  words: [
    withPage({ word: "achieve", partOfSpeech: "verb", meaning: "To reach a goal through effort.", example: "The team achieved a record result in the final quarter." }),
    withPage({ word: "create", partOfSpeech: "verb", meaning: "To make something original.", example: "The designer created a layout that balanced clarity and beauty." }),
    withPage({ word: "discover", partOfSpeech: "verb", meaning: "To find or learn something previously unknown.", example: "Researchers discovered a more efficient way to store solar energy." }),
    withPage({ word: "challenge", partOfSpeech: "verb", meaning: "To question or dispute; to push limits.", example: "She challenged the assumption that the process could not be improved." }),
    withPage({ word: "understand", partOfSpeech: "verb", meaning: "To perceive or grasp the meaning of something.", example: "Leaders who understand their team build stronger results." }),
    noPage({ word: "execute", partOfSpeech: "verb", meaning: "To carry out a plan or task completely.", example: "She executed the strategy without hesitation." }),
    noPage({ word: "transform", partOfSpeech: "verb", meaning: "To change completely in form or nature.", example: "The renovation transformed the old building into a modern workspace." }),
    noPage({ word: "drive", partOfSpeech: "verb", meaning: "To push forward; to motivate or cause.", example: "Data drives every decision in the analytics team." }),
    noPage({ word: "build", partOfSpeech: "verb", meaning: "To construct or develop over time.", example: "She spent five years building a reputation for quality." }),
    noPage({ word: "lead", partOfSpeech: "verb", meaning: "To guide, direct, or go first.", example: "He led the team through a difficult transition period." }),
    noPage({ word: "solve", partOfSpeech: "verb", meaning: "To find an answer to a problem.", example: "The new process solved the bottleneck in the supply chain." }),
    noPage({ word: "launch", partOfSpeech: "verb", meaning: "To start or release something new.", example: "They launched the product after months of testing." }),
    noPage({ word: "expand", partOfSpeech: "verb", meaning: "To grow larger or wider in scope.", example: "The company plans to expand into three new markets next year." }),
    noPage({ word: "deliver", partOfSpeech: "verb", meaning: "To bring something to where it is needed; to produce a result.", example: "The team consistently delivers on tight deadlines." }),
    noPage({ word: "streamline", partOfSpeech: "verb", meaning: "To make a process simpler and more efficient.", example: "They streamlined the application process from ten steps to four." }),
    noPage({ word: "empower", partOfSpeech: "verb", meaning: "To give someone the tools or authority to act.", example: "The training empowered staff to solve problems independently." }),
    noPage({ word: "establish", partOfSpeech: "verb", meaning: "To set up or prove something firmly.", example: "She established clear expectations at the beginning of the project." }),
    noPage({ word: "negotiate", partOfSpeech: "verb", meaning: "To reach an agreement through discussion.", example: "He negotiated a better rate with the supplier." }),
    noPage({ word: "accelerate", partOfSpeech: "verb", meaning: "To increase in speed or make faster.", example: "The investment accelerated growth by two years." }),
    noPage({ word: "communicate", partOfSpeech: "verb", meaning: "To share information clearly with others.", example: "Good managers communicate decisions before they take effect." }),
    noPage({ word: "implement", partOfSpeech: "verb", meaning: "To put a plan or decision into action.", example: "The new policy was implemented across all departments." }),
    noPage({ word: "collaborate", partOfSpeech: "verb", meaning: "To work together toward a shared goal.", example: "Teams that collaborate tend to produce better solutions." }),
    noPage({ word: "analyse", partOfSpeech: "verb", meaning: "To examine in detail to understand.", example: "She analysed the data and identified three key trends." }),
    noPage({ word: "evaluate", partOfSpeech: "verb", meaning: "To assess the quality or value of something.", example: "The board will evaluate all proposals by Friday." }),
    noPage({ word: "prioritise", partOfSpeech: "verb", meaning: "To decide the order of importance and act accordingly.", example: "In a busy week, you have to prioritise ruthlessly." }),
    noPage({ word: "improve", partOfSpeech: "verb", meaning: "To make or become better.", example: "They focused on improving the user experience first." }),
    noPage({ word: "define", partOfSpeech: "verb", meaning: "To state the meaning or scope of something clearly.", example: "Before starting, define what success looks like." }),
    noPage({ word: "measure", partOfSpeech: "verb", meaning: "To quantify or assess the size or quality of something.", example: "You cannot manage what you cannot measure." }),
    noPage({ word: "influence", partOfSpeech: "verb", meaning: "To have an effect on someone or something.", example: "Good design influences how users feel about a product." }),
    noPage({ word: "inspire", partOfSpeech: "verb", meaning: "To fill someone with motivation or creative energy.", example: "A strong mission inspires people to put in extra effort." }),
    noPage({ word: "exceed", partOfSpeech: "verb", meaning: "To go beyond a limit or expectation.", example: "Sales exceeded projections by 30% in the first quarter." }),
    noPage({ word: "engage", partOfSpeech: "verb", meaning: "To attract and hold someone's attention or involvement.", example: "The campaign engaged thousands of new users in its first week." }),
    noPage({ word: "leverage", partOfSpeech: "verb", meaning: "To use something to its full advantage.", example: "Smart companies leverage data to make faster decisions." }),
    noPage({ word: "support", partOfSpeech: "verb", meaning: "To help, uphold, or provide resources for.", example: "The manager supported her through the learning curve." }),
    noPage({ word: "demonstrate", partOfSpeech: "verb", meaning: "To show or prove something clearly.", example: "Her results demonstrate that the method works." }),
    noPage({ word: "generate", partOfSpeech: "verb", meaning: "To produce or create something.", example: "The campaign generated significant interest from new clients." }),
    noPage({ word: "simplify", partOfSpeech: "verb", meaning: "To make easier to understand or do.", example: "The redesign simplified the checkout process to two steps." }),
    noPage({ word: "validate", partOfSpeech: "verb", meaning: "To confirm or prove that something is correct or effective.", example: "User testing validates assumptions before full development begins." }),
    noPage({ word: "craft", partOfSpeech: "verb", meaning: "To make or create with care and skill.", example: "He crafted each paragraph with precision and purpose." }),
    noPage({ word: "pursue", partOfSpeech: "verb", meaning: "To follow or work toward something with determination.", example: "She decided to pursue a career in environmental science." }),
  ],
};

// ── List 6: 40 Descriptive Adjectives ─────────────────────────────
export const descriptiveAdjectives = {
  id: "descriptive-adjectives",
  audience: "Writers and students describing people, places, and things.",
  useCases: ["Add specific, sensory detail to descriptions","Avoid overused adjectives like “good” or “big”","Build richer character and setting descriptions"],
  tip: "Choose adjectives a reader can picture — “serene” beats “very calm”.",
  href: "/word-lists/descriptive-adjectives/",
  title: "40 Descriptive Adjectives for Precise and Vivid Language",
  h1: "40 Descriptive Adjectives",
  metaTitle: "40 Descriptive Adjectives for Precise and Vivid Language | Word Helper",
  metaDescription:
    "Go beyond basic adjectives with 40 descriptive words that paint clearer pictures. Each includes a meaning and example sentence.",
  intro: "Forty precise adjectives to describe people, places, and things with more detail and originality.",
  answer:
    "Most writers default to the same ten adjectives: good, bad, big, small, nice, great. These 40 descriptive adjectives replace vague language with precise, vivid alternatives that create clearer mental pictures and stronger writing.",
  category: "Writing",
  difficulty: "intermediate",
  wordCount: 40,
  words: [
    withPage({ word: "beautiful", partOfSpeech: "adjective", meaning: "Extremely pleasing to the senses or the mind.", example: "The stone path through the garden was beautiful in autumn." }),
    withPage({ word: "powerful", partOfSpeech: "adjective", meaning: "Having great strength or effect.", example: "The documentary was a powerful reminder of why the work matters." }),
    withPage({ word: "simple", partOfSpeech: "adjective", meaning: "Not complicated; easy to understand or use.", example: "A simple design often communicates more than a complex one." }),
    withPage({ word: "amazing", partOfSpeech: "adjective", meaning: "Causing great wonder or surprise.", example: "The speed of the transformation was amazing to witness." }),
    withPage({ word: "excellent", partOfSpeech: "adjective", meaning: "Extremely good; meeting a very high standard.", example: "The restaurant received excellent reviews for its seasonal menu." }),
    noPage({ word: "precise", partOfSpeech: "adjective", meaning: "Exact and accurate, with no room for error.", example: "The surgeon's movements were precise and controlled." }),
    noPage({ word: "subtle", partOfSpeech: "adjective", meaning: "Not obvious; delicate and easily missed.", example: "There was a subtle change in his tone after the news." }),
    noPage({ word: "stark", partOfSpeech: "adjective", meaning: "Sharply clear and plain; harsh and bare.", example: "The contrast between old and new architecture was stark." }),
    noPage({ word: "intricate", partOfSpeech: "adjective", meaning: "Very detailed and complex in design.", example: "The jewellery featured intricate patterns across the surface." }),
    noPage({ word: "vast", partOfSpeech: "adjective", meaning: "Extremely large in size or extent.", example: "A vast plain stretched to the horizon in every direction." }),
    noPage({ word: "hollow", partOfSpeech: "adjective", meaning: "Empty inside; without real meaning or feeling.", example: "His apology felt hollow because no change followed it." }),
    noPage({ word: "radiant", partOfSpeech: "adjective", meaning: "Sending out bright light or strong positive energy.", example: "She was radiant on the day of her graduation." }),
    noPage({ word: "fragile", partOfSpeech: "adjective", meaning: "Easily broken or damaged; delicate.", example: "Peace in the region is still fragile and could change quickly." }),
    noPage({ word: "vibrant", partOfSpeech: "adjective", meaning: "Full of energy and life; bright and striking.", example: "The vibrant neighbourhood was full of restaurants and music." }),
    noPage({ word: "serene", partOfSpeech: "adjective", meaning: "Calm, peaceful, and undisturbed.", example: "The lake was serene at dawn, with no wind or sound." }),
    noPage({ word: "grim", partOfSpeech: "adjective", meaning: "Forbidding and unappealing; very serious and unpleasant.", example: "The report painted a grim picture of the city's finances." }),
    noPage({ word: "lush", partOfSpeech: "adjective", meaning: "Growing thickly and richly; luxuriously full.", example: "The valley was lush with ferns and mosses after the rain." }),
    noPage({ word: "narrow", partOfSpeech: "adjective", meaning: "Small in width; limited in range.", example: "The narrow street made it difficult for cars to pass." }),
    noPage({ word: "solemn", partOfSpeech: "adjective", meaning: "Serious, formal, and often sad.", example: "The ceremony had a solemn atmosphere that everyone respected." }),
    noPage({ word: "turbulent", partOfSpeech: "adjective", meaning: "Full of disorder or confusion; violently unsettled.", example: "It was a turbulent period in the company's history." }),
    noPage({ word: "brisk", partOfSpeech: "adjective", meaning: "Active, quick, and energetic.", example: "A brisk walk in the morning helps clear the mind." }),
    noPage({ word: "dense", partOfSpeech: "adjective", meaning: "Closely packed; difficult to pass through or understand.", example: "The forest was dense with old trees and undergrowth." }),
    noPage({ word: "elusive", partOfSpeech: "adjective", meaning: "Difficult to find, define, or catch.", example: "The perfect word for the feeling remained elusive." }),
    noPage({ word: "faint", partOfSpeech: "adjective", meaning: "Not clearly seen, heard, or felt; weak.", example: "There was a faint smell of smoke from the fireplace." }),
    noPage({ word: "crisp", partOfSpeech: "adjective", meaning: "Firm, fresh, and clear; not soggy or dull.", example: "The morning air was crisp and cold." }),
    noPage({ word: "fluid", partOfSpeech: "adjective", meaning: "Able to flow; smooth and adaptable.", example: "The dancer's movements were fluid and perfectly controlled." }),
    noPage({ word: "steady", partOfSpeech: "adjective", meaning: "Not moving or changing; reliable and consistent.", example: "Her voice remained steady even during the difficult part of the speech." }),
    noPage({ word: "bitter", partOfSpeech: "adjective", meaning: "Having a sharp, unpleasant taste; feeling anger or hurt.", example: "He was bitter about the outcome for months afterward." }),
    noPage({ word: "blunt", partOfSpeech: "adjective", meaning: "Direct and honest, sometimes to the point of rudeness; not sharp.", example: "She was blunt about the flaws in the proposal." }),
    noPage({ word: "robust", partOfSpeech: "adjective", meaning: "Strong, healthy, and able to withstand difficulty.", example: "The system needs a more robust solution before it can scale." }),
    noPage({ word: "sparse", partOfSpeech: "adjective", meaning: "Thin, scanty, and not densely packed.", example: "Vegetation was sparse in the higher parts of the mountain." }),
    noPage({ word: "sharp", partOfSpeech: "adjective", meaning: "Cutting; clear and intense; intelligent.", example: "Her sharp eye noticed the error before anyone else." }),
    noPage({ word: "muted", partOfSpeech: "adjective", meaning: "Softened in tone or colour; quiet and restrained.", example: "The room was decorated in muted shades of grey and green." }),
    noPage({ word: "bold", partOfSpeech: "adjective", meaning: "Confident, brave, and striking.", example: "The logo redesign was bold and immediately recognisable." }),
    noPage({ word: "timid", partOfSpeech: "adjective", meaning: "Showing a lack of confidence or courage.", example: "His timid approach made it hard to negotiate effectively." }),
    noPage({ word: "ancient", partOfSpeech: "adjective", meaning: "Very old, often from a remote historical period.", example: "The ancient walls of the city still stood after two thousand years." }),
    noPage({ word: "relentless", partOfSpeech: "adjective", meaning: "Continuing without stopping or weakening.", example: "The relentless rain delayed the outdoor event." }),
    noPage({ word: "fleeting", partOfSpeech: "adjective", meaning: "Lasting for only a short time.", example: "The moment of joy was fleeting but genuinely felt." }),
    noPage({ word: "hollow", partOfSpeech: "adjective", meaning: "Empty inside; without substance or sincerity.", example: "The promise felt hollow when nothing changed in the weeks that followed." }),
    noPage({ word: "familiar", partOfSpeech: "adjective", meaning: "Well-known from experience; easy to recognise.", example: "The smell of coffee was familiar and comforting." }),
  ],
};

export const wordLists = [
  commonEnglishWords,
  positiveWords,
  academicWords,
  wordsForWriters,
  strongActionVerbs,
  descriptiveAdjectives,
];
